version: '3.7'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "8001:5432"
  app:
    build: ..
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - "db"